
import type { Station } from './types';

// This file is now a backup and is no longer directly used by the application.
// Station data is fetched from Firestore.
export const stations: Station[] = [
  {
    id: 'station-1',
    name: 'EcoCharge Central',
    address: '123 Green Energy Ave',
    city: 'Voltville',
    country: 'USA',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    mobileNumber: '+1 (555) 123-4567',
    amenities: ['Wi-Fi', 'Cafe', 'Restroom'],
    rating: 4.8,
    reviewCount: 256,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'electric car',
    bunks: [
      { id: 'bunk-1a', name: 'Bunk A1', status: 'available' },
      { id: 'bunk-1b', name: 'Bunk A2', status: 'occupied' },
      { id: 'bunk-1c', name: 'Bunk A3', status: 'available' },
      { id: 'bunk-1d', name: 'Bunk B1', status: 'maintenance' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-2',
    name: 'PowerUp Plaza',
    address: '456 Lightning Ln',
    city: 'Ampere City',
    country: 'USA',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    mobileNumber: '+1 (555) 987-6543',
    amenities: ['Lounge', 'Vending Machine'],
    rating: 4.5,
    reviewCount: 189,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'charging station',
     bunks: [
      { id: 'bunk-2a', name: 'Bunk 1', status: 'available' },
      { id: 'bunk-2b', name: 'Bunk 2', status: 'available' },
      { id: 'bunk-2c', name: 'Bunk 3', status: 'occupied' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: false },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: false },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-3',
    name: 'Volt Valley',
    address: '789 Circuit Dr',
    city: 'Voltville',
    country: 'USA',
    coordinates: { lat: 40.7580, lng: -73.9855 },
    mobileNumber: '+1 (555) 234-5678',
    amenities: ['Wi-Fi', 'Restroom'],
    rating: 4.6,
    reviewCount: 312,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'electric vehicle',
     bunks: [
      { id: 'bunk-3a', name: 'Spot 1', status: 'available' },
      { id: 'bunk-3b', name: 'Spot 2', status: 'occupied' },
      { id: 'bunk-3c', name: 'Spot 3', status: 'occupied' },
      { id: 'bunk-3d', name: 'Spot 4', status: 'available' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: false },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: false },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-4',
    name: 'ChargeGrid Mumbai',
    address: '101 Electric Avenue, Bandra',
    city: 'Mumbai',
    country: 'India',
    coordinates: { lat: 19.0760, lng: 72.8777 },
    mobileNumber: '+91 (22) 5555-1234',
    amenities: ['Wi-Fi', 'Restroom', 'Cafe'],
    rating: 4.7,
    reviewCount: 150,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'electric car charging',
     bunks: [
      { id: 'bunk-4a', name: 'Bay 1', status: 'available' },
      { id: 'bunk-4b', name: 'Bay 2', status: 'available' },
      { id: 'bunk-4c', name: 'Bay 3', status: 'occupied' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: false },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-5',
    name: 'EV Plugs Vizag',
    address: '202 Beach Road',
    city: 'Visakhapatnam',
    country: 'India',
    coordinates: { lat: 17.6868, lng: 83.2185 },
    mobileNumber: '+91 (891) 5555-5678',
    amenities: ['Lounge', 'Restroom'],
    rating: 4.6,
    reviewCount: 95,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'ev charging india',
     bunks: [
      { id: 'bunk-5a', name: 'Charger 1', status: 'available' },
      { id: 'bunk-5b', name: 'Charger 2', status: 'occupied' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: false },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-6',
    name: 'Ather Grid - Koramangala',
    address: '100ft Road, Koramangala',
    city: 'Bangalore',
    country: 'India',
    coordinates: { lat: 12.9352, lng: 77.6245 },
    mobileNumber: '+91 (80) 5555-9876',
    amenities: ['Wi-Fi', 'Cafe'],
    rating: 4.9,
    reviewCount: 450,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'modern city street',
    bunks: [
      { id: 'bunk-6a', name: 'Ather-1', status: 'available' },
      { id: 'bunk-6b', name: 'Ather-2', status: 'occupied' },
      { id: 'bunk-6c', name: 'Ather-3', status: 'maintenance' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-7',
    name: 'Tata Power EZ Charge - Connaught Place',
    address: 'Inner Circle, Connaught Place',
    city: 'Delhi',
    country: 'India',
    coordinates: { lat: 28.6324, lng: 77.2187 },
    mobileNumber: '+91 (11) 5555-4321',
    amenities: ['Restroom', 'Lounge'],
    rating: 4.6,
    reviewCount: 320,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'urban infrastructure',
    bunks: [
      { id: 'bunk-7a', name: 'Charger A', status: 'available' },
      { id: 'bunk-7b', name: 'Charger B', status: 'occupied' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: false },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: false },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-8',
    name: 'Ionity Charging Hub - Alexanderplatz',
    address: 'Alexanderpl. 1, 10178 Berlin',
    city: 'Berlin',
    country: 'Germany',
    coordinates: { lat: 52.5219, lng: 13.4132 },
    mobileNumber: '+49 (30) 1234-5678',
    amenities: ['Wi-Fi', 'Cafe', 'Restroom'],
    rating: 4.7,
    reviewCount: 512,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'european city square',
    bunks: [
      { id: 'bunk-8a', name: 'Hub 1', status: 'available' },
      { id: 'bunk-8b', name: 'Hub 2', status: 'available' },
      { id: 'bunk-8c', name: 'Hub 3', status: 'occupied' },
      { id: 'bunk-8d', name: 'Hub 4', status: 'available' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-9',
    name: 'ChargePoint - Canary Wharf',
    address: '1 Canada Square, London E14 5AB',
    city: 'London',
    country: 'UK',
    coordinates: { lat: 51.5054, lng: -0.0235 },
    mobileNumber: '+44 20 7123 4567',
    amenities: ['Wi-Fi', 'Lounge'],
    rating: 4.8,
    reviewCount: 620,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'london skyscraper',
    bunks: [
      { id: 'bunk-9a', name: 'CP-01', status: 'available' },
      { id: 'bunk-9b', name: 'CP-02', status: 'maintenance' },
      { id: 'bunk-9c', name: 'CP-03', status: 'available' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: false },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: false },
    ],
  },
  {
    id: 'station-10',
    name: 'Hitech Power Grid',
    address: 'Hitech City Main Rd, Madhapur',
    city: 'Hyderabad',
    country: 'India',
    coordinates: { lat: 17.4483, lng: 78.3915 },
    mobileNumber: '+91 (40) 5555-8888',
    amenities: ['Wi-Fi', 'Cafe'],
    rating: 4.7,
    reviewCount: 210,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'modern city india',
    bunks: [
      { id: 'bunk-10a', name: 'Charger A', status: 'available' },
      { id: 'bunk-10b', name: 'Charger B', status: 'available' },
      { id: 'bunk-10c', name: 'Charger C', status: 'occupied' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: false },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: false },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-11',
    name: 'Goa Coastal Charge',
    address: 'Baga Beach Rd, Calangute',
    city: 'Goa',
    country: 'India',
    coordinates: { lat: 15.5573, lng: 73.7547 },
    mobileNumber: '+91 (832) 5555-7777',
    amenities: ['Restroom', 'Lounge'],
    rating: 4.5,
    reviewCount: 130,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'beach sunset',
    bunks: [
      { id: 'bunk-11a', name: 'Slot 1', status: 'available' },
      { id: 'bunk-11b', name: 'Slot 2', status: 'occupied' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: false },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-12',
    name: 'Pune Power Point',
    address: 'Koregaon Park',
    city: 'Pune',
    country: 'India',
    coordinates: { lat: 18.5362, lng: 73.8939 },
    mobileNumber: '+91 (20) 5555-6666',
    amenities: ['Wi-Fi', 'Vending Machine'],
    rating: 4.6,
    reviewCount: 195,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'green park city',
    bunks: [
      { id: 'bunk-12a', name: 'Point A', status: 'available' },
      { id: 'bunk-12b', name: 'Point B', status: 'available' },
      { id: 'bunk-12c', name: 'Point C', status: 'maintenance' },
    ],
    slots: [
      { time: '09:00 AM', available: false },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-13',
    name: 'Marina Power Hub',
    address: 'T. Nagar',
    city: 'Chennai',
    country: 'India',
    coordinates: { lat: 13.0475, lng: 80.2403 },
    mobileNumber: '+91 (44) 5555-5555',
    amenities: ['Cafe', 'Restroom'],
    rating: 4.8,
    reviewCount: 350,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'temple architecture india',
    bunks: [
      { id: 'bunk-13a', name: 'Hub 1', status: 'occupied' },
      { id: 'bunk-13b', name: 'Hub 2', status: 'available' },
      { id: 'bunk-13c', name: 'Hub 3', status: 'available' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: false },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-14',
    name: 'Paradise Charge Kashmir',
    address: 'Dal Lake Front',
    city: 'Srinagar',
    country: 'India',
    coordinates: { lat: 34.0837, lng: 74.7973 },
    mobileNumber: '+91 (194) 5555-4444',
    amenities: ['Lounge'],
    rating: 4.9,
    reviewCount: 85,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'mountain lake',
    bunks: [
      { id: 'bunk-14a', name: 'Spot 1', status: 'available' },
      { id: 'bunk-14b', name: 'Spot 2', status: 'available' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: false },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: false },
    ],
  },
  {
    id: 'station-15',
    name: 'Tokyo EV Fast Charge',
    address: 'Shibuya Crossing',
    city: 'Tokyo',
    country: 'Japan',
    coordinates: { lat: 35.6595, lng: 139.7005 },
    mobileNumber: '+81 3-1234-5678',
    amenities: ['Wi-Fi', 'Vending Machine', 'Restroom'],
    rating: 4.9,
    reviewCount: 800,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'tokyo street night',
    bunks: [
      { id: 'bunk-15a', name: 'Fast-1', status: 'occupied' },
      { id: 'bunk-15b', name: 'Fast-2', status: 'occupied' },
      { id: 'bunk-15c', name: 'Fast-3', status: 'available' },
      { id: 'bunk-15d', name: 'Fast-4', status: 'available' },
    ],
    slots: [
      { time: '09:00 AM', available: false },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-16',
    name: 'Sydney Harbour E-Fill',
    address: 'Circular Quay',
    city: 'Sydney',
    country: 'Australia',
    coordinates: { lat: -33.8601, lng: 151.2118 },
    mobileNumber: '+61 2 9876 5432',
    amenities: ['Cafe', 'Lounge'],
    rating: 4.8,
    reviewCount: 410,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sydney opera house',
    bunks: [
      { id: 'bunk-16a', name: 'Dock A', status: 'available' },
      { id: 'bunk-16b', name: 'Dock B', status: 'maintenance' },
      { id: 'bunk-16c', name: 'Dock C', status: 'available' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: true },
      { time: '11:00 AM', available: false },
      { time: '12:00 PM', available: true },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: false },
      { time: '04:00 PM', available: true },
    ],
  },
  {
    id: 'station-17',
    name: 'Paris-Volt - Tour Eiffel',
    address: 'Champ de Mars',
    city: 'Paris',
    country: 'France',
    coordinates: { lat: 48.8584, lng: 2.2945 },
    mobileNumber: '+33 1 87 65 43 21',
    amenities: ['Wi-Fi', 'Cafe'],
    rating: 4.7,
    reviewCount: 750,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'eiffel tower',
    bunks: [
      { id: 'bunk-17a', name: 'Volt-1', status: 'available' },
      { id: 'bunk-17b', name: 'Volt-2', status: 'occupied' },
    ],
    slots: [
      { time: '09:00 AM', available: true },
      { time: '10:00 AM', available: false },
      { time: '11:00 AM', available: true },
      { time: '12:00 PM', available: false },
      { time: '01:00 PM', available: true },
      { time: '02:00 PM', available: true },
      { time: '03:00 PM', available: true },
      { time: '04:00 PM', available: true },
    ],
  },
];

    